### PR TITLE
Error Uri is too long 

### PR DESCRIPTION
**Pull request by peache85**
When Post data is too long to be encoded as FromUrl it uses a Json serialization to support big amont of data

### CODE REVIEW

**Comment by floriansegginger** [comment]
This requires an update of the specificiations and a new version of the protocol, as POST requests are defined to be `application/x-www-form-urlencoded`.

**Comment by floriansegginger** [comment]
To clarify, I believe the specs should mention support for both methods in my opinion. Encoding POST data in JSON is "relatively new" and cannot be done with a basic HTML form (which uses `application/x-www-form-urlencoded`).

**Comment by peache85** [comment]
> To clarify, I believe the specs should mention support for both methods in my opinion. Encoding POST data in JSON is "relatively new" and cannot be done with a basic HTML form (which uses `application/x-www-form-urlencoded`).

Thanks for your comments. It’s very appreciated. I think it is better to not change the spec of the protocol for this very rare error case  (not encountered since years of use)

**Review by francoisbirling — APPROVED** [review]

**Comment by floriansegginger** [comment]
@peache85 if this is a modification that's been implemented in the server and the client, then it should definitely be mentioned in the specifications. A minor update (1.2.1) along with a few words in the specs page will be more than enough.

**Pull request merged**
